name: to_do_app
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev.
publish_to: "none" # Remove this line if you wish to publish to pub.dev.

# Define the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^14.0.0
  table_calendar: ^3.0.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^1.1.3
  flutter_lints: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
